insert into CURRECNY_EXCHANGE (ID,CURRENCY_FROM,CURRENCY_TO,CONVERSTION_MULTIPLE ,APPLICATION_PORT_NUMBER )
values (1001,'USD','INR',80,'');
insert into CURRECNY_EXCHANGE (ID,CURRENCY_FROM,CURRENCY_TO,CONVERSTION_MULTIPLE ,APPLICATION_PORT_NUMBER )
values (1002,'EUR','INR',75,'');
insert into CURRECNY_EXCHANGE (ID,CURRENCY_FROM,CURRENCY_TO,CONVERSTION_MULTIPLE ,APPLICATION_PORT_NUMBER )
values (1003,'AUD','INR',25,'');
